/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Filme;
import locadora.random.play.Genero;
import locadora.random.play.persistencia.FilmeDAOImplPsql;
import locadora.random.play.persistencia.GeneroDAOImplPsql;

/**
 *
 * @author kauan
 */
public class CadastraFilmeJPanel extends javax.swing.JPanel {
    private GeneroDAOImplPsql bancoGenero = new GeneroDAOImplPsql();
    private FilmeDAOImplPsql bancoFilme = new FilmeDAOImplPsql();
    private List<Genero> listaGeneros = new ArrayList<>();
    private List<Genero> generosSelecionados = new ArrayList<>();

    /**
     * Creates new form FilmeJPanel
     */
    public CadastraFilmeJPanel() {
        initComponents();
        generosJComboBox.removeAllItems();
        carregarMenuGeneros();
        carregarTabelaFilmes();
    }
    private void carregarMenuGeneros(){
        listaGeneros = bancoGenero.consultar();
        for (Genero genero : listaGeneros) {
            generosJComboBox.addItem(genero.getDescricao());
        }
    }
    
    private void adicionaGenero(Genero generoNovo){
        if (generosSelecionados.contains(generoNovo)){
            throw new RuntimeException("Gênero já foi adicionado");
        }else{
            generosSelecionados.add(generoNovo);
        }
    }
    
    private void removeGenero(Genero generoARemover){
        if (!generosSelecionados.contains(generoARemover)){
            throw new RuntimeException("Gênero não foi adicionado");
        }else{
            generosSelecionados.remove(generoARemover);
        }
    }
    
    private void mostraGeneros(){
        String generosStr = "";
        for (Genero g : generosSelecionados){
            if(generosStr.equals("")){
                generosStr = g.getDescricao();
            }else{
                generosStr += ", " + g.getDescricao();
            }
        }
        generosJTextField.setText(generosStr);
    }
    

    
    private void carregarTabelaFilmes(){
        DefaultTableModel dfm = (DefaultTableModel) filmesJTable.getModel();
        dfm.setRowCount(0);
        List<Filme> lista = bancoFilme.consultarLimitado(20, false);
        for (Filme filme : lista) {
            Object[] linha = new Object[3];
            linha[0] = filme.getId();
            linha[1] = filme.getTitulo();
            linha[2] = filme.getQntdEstoque();
            dfm.addRow(linha);
        }
    }
    private void resultaBuscaTitulo(String titulo){
        DefaultTableModel dfm = (DefaultTableModel) filmesJTable.getModel();
        dfm.setRowCount(0);
        
        List<Filme> lista = bancoFilme.buscar(titulo, false);
        for (Filme filme : lista) {
            Object[] linha = new Object[3];
            linha[0] = filme.getId();
            linha[1] = filme.getTitulo();
            linha[2] = filme.getQntdEstoque();
            dfm.addRow(linha);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaExclJDialog = new javax.swing.JDialog();
        simJButton = new javax.swing.JButton();
        naoJButton = new javax.swing.JButton();
        textoExclJLabel = new javax.swing.JLabel();
        textoCadastroJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        idJLabel = new javax.swing.JLabel();
        tituloJLabel = new javax.swing.JLabel();
        autorJLabel = new javax.swing.JLabel();
        descriçãoJLabel = new javax.swing.JLabel();
        duracaoJLabel = new javax.swing.JLabel();
        valorJLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        filmesJTable = new javax.swing.JTable();
        adicionarGeneroJButton = new javax.swing.JButton();
        tituloJLabel1 = new javax.swing.JLabel();
        buscarJButton = new javax.swing.JButton();
        buscaJTextField = new javax.swing.JTextField();
        removerJButton = new javax.swing.JButton();
        tituloJTextField = new javax.swing.JTextField();
        autorJTextField = new javax.swing.JTextField();
        descricaoJTextField = new javax.swing.JTextField();
        duracaoJTextField = new javax.swing.JTextField();
        valorJTextField = new javax.swing.JTextField();
        generosJLabel = new javax.swing.JLabel();
        generosJTextField = new javax.swing.JTextField();
        cadastrarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();
        generosJComboBox = new javax.swing.JComboBox<>();
        editarJButton = new javax.swing.JButton();
        qntdJLabel = new javax.swing.JLabel();
        qntdJTextField = new javax.swing.JTextField();
        removerGeneroJButton = new javax.swing.JButton();

        confirmaExclJDialog.setSize(new java.awt.Dimension(330, 190));

        simJButton.setText("Sim");
        simJButton.addActionListener(this::simJButtonActionPerformed);

        naoJButton.setText("Não");
        naoJButton.addActionListener(this::naoJButtonActionPerformed);

        textoExclJLabel.setText("TEXTO DE EXCLUSÃO");

        javax.swing.GroupLayout confirmaExclJDialogLayout = new javax.swing.GroupLayout(confirmaExclJDialog.getContentPane());
        confirmaExclJDialog.getContentPane().setLayout(confirmaExclJDialogLayout);
        confirmaExclJDialogLayout.setHorizontalGroup(
            confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoExclJLabel)
                    .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                        .addComponent(simJButton)
                        .addGap(39, 39, 39)
                        .addComponent(naoJButton)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        confirmaExclJDialogLayout.setVerticalGroup(
            confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(textoExclJLabel)
                .addGap(40, 40, 40)
                .addGroup(confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simJButton)
                    .addComponent(naoJButton))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        textoCadastroJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textoCadastroJLabel.setText("CADASTRAR FILME");

        idJTextField.setEditable(false);
        idJTextField.setEnabled(false);
        idJTextField.addActionListener(this::idJTextFieldActionPerformed);

        idJLabel.setText("ID:");

        tituloJLabel.setText("Titulo:");

        autorJLabel.setText("Autor (Direção):");

        descriçãoJLabel.setText("Descrição:");

        duracaoJLabel.setText("Duração (Minutos):");

        valorJLabel.setText("Valor da Locação (Semanal):");

        filmesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Qntd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        filmesJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(filmesJTable);

        adicionarGeneroJButton.setText("Adicionar");
        adicionarGeneroJButton.addActionListener(this::adicionarGeneroJButtonActionPerformed);

        tituloJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloJLabel1.setText("FILMES CADASTRADOS");

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(this::buscarJButtonActionPerformed);

        buscaJTextField.addActionListener(this::buscaJTextFieldActionPerformed);

        removerJButton.setText("Remover Filme");
        removerJButton.addActionListener(this::removerJButtonActionPerformed);

        generosJLabel.setText("Generos (Adicione pelo menu):");

        generosJTextField.setEditable(false);

        cadastrarJButton.setText("Cadastrar");
        cadastrarJButton.addActionListener(this::cadastrarJButtonActionPerformed);

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        generosJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        generosJComboBox.addActionListener(this::generosJComboBoxActionPerformed);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        qntdJLabel.setText("Quantidade Estoque:");

        removerGeneroJButton.setText("Remover Gênero");
        removerGeneroJButton.addActionListener(this::removerGeneroJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoCadastroJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloJLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editarJButton)
                        .addGap(60, 60, 60)
                        .addComponent(removerJButton)
                        .addGap(23, 23, 23)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(generosJLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valorJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(valorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(descriçãoJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(descricaoJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(duracaoJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(duracaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(idJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tituloJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(tituloJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(autorJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(autorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(generosJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(adicionarGeneroJButton)
                            .addGap(18, 18, 18)
                            .addComponent(removerGeneroJButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(qntdJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(qntdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(generosJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarJButton)
                        .addGap(54, 54, 54)
                        .addComponent(cancelarJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarJButton)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCadastroJLabel)
                    .addComponent(tituloJLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarJButton)
                            .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idJLabel)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloJLabel)
                            .addComponent(tituloJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autorJLabel)
                            .addComponent(autorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriçãoJLabel)
                            .addComponent(descricaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duracaoJLabel)
                            .addComponent(duracaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorJLabel)
                            .addComponent(valorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(generosJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(generosJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generosJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionarGeneroJButton)
                            .addComponent(removerGeneroJButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qntdJLabel)
                            .addComponent(qntdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarJButton)
                            .addComponent(cancelarJButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removerJButton)
                    .addComponent(editarJButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJTextFieldActionPerformed

    private void cadastrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJButtonActionPerformed
        try {
            String textoValor = valorJTextField.getText();
            textoValor = textoValor.replace(",", ".");
            double valor = Double.parseDouble(textoValor);
            
            String textoDuracao = duracaoJTextField.getText();
            int duracao = Integer.parseInt(textoDuracao);
            
            String textoQuantidade = qntdJTextField.getText();
            int qntd = Integer.parseInt(textoQuantidade);
            Filme novoFilme = new Filme(tituloJTextField.getText(), autorJTextField.getText(), descricaoJTextField.getText(), valor, qntd, duracao, generosSelecionados);
            String idStr = idJTextField.getText();  
            try {
                int id = Integer.parseInt(idStr);
                novoFilme.setId(id);
                bancoFilme.atualizar(novoFilme);
                JOptionPane.showMessageDialog(cadastrarJButton, "Filme atualizado!");  
                cancelarJButtonActionPerformed(evt);
            } catch(NumberFormatException erro){
            //Verificar se o filme já está no sistema
                List<Filme> listaFilme = bancoFilme.consultar(false);
                String titulo = novoFilme.getTitulo();
                boolean cadastrado = false;
                for (Filme f : listaFilme){
                if (f.getTitulo().equals(titulo)){
                    JOptionPane.showMessageDialog(cadastrarJButton, "Filme já registrado!");
                    cadastrado = true;
                    break;
                }
            }        
            //Fim verificaçõa
            if (!cadastrado){
                bancoFilme.inserir(novoFilme);
                JOptionPane.showMessageDialog(cadastrarJButton, "Filme cadastrado com sucesso!");
                cancelarJButtonActionPerformed(evt);
            }}
        
            } catch(Exception erro) {
            erro.printStackTrace();
            JOptionPane.showMessageDialog(cadastrarJButton, erro.getMessage());
        }
        carregarTabelaFilmes();
    }//GEN-LAST:event_cadastrarJButtonActionPerformed

    private void generosJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generosJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generosJComboBoxActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        idJTextField.setText("");
        tituloJTextField.setText("");
        autorJTextField.setText("");
        descricaoJTextField.setText("");
        duracaoJTextField.setText("");
        valorJTextField.setText("");
        generosJTextField.setText("");
        qntdJTextField.setText("");
        generosSelecionados = new ArrayList<>();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void buscaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaJTextFieldActionPerformed

    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarJButtonActionPerformed
        if (buscaJTextField.getText().isBlank()){
            JOptionPane.showMessageDialog(buscaJTextField, "Digite um titulo!");
        }else{
            resultaBuscaTitulo(buscaJTextField.getText());
        }
    }//GEN-LAST:event_buscarJButtonActionPerformed

    private void adicionarGeneroJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGeneroJButtonActionPerformed
        try{
            adicionaGenero(listaGeneros.get(generosJComboBox.getSelectedIndex()));
            mostraGeneros();    
        } catch (Exception erro){
            erro.printStackTrace();
            JOptionPane.showMessageDialog(cadastrarJButton, erro.getMessage());
        }
        
    }//GEN-LAST:event_adicionarGeneroJButtonActionPerformed

    private void removerGeneroJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerGeneroJButtonActionPerformed
        try{
            removeGenero(listaGeneros.get(generosJComboBox.getSelectedIndex()));
            mostraGeneros();    
        } catch (Exception erro){
            erro.printStackTrace();
            JOptionPane.showMessageDialog(cadastrarJButton, erro.getMessage());
        }
    }//GEN-LAST:event_removerGeneroJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        if (filmesJTable.getSelectedRowCount() == 1){
            int linha = filmesJTable.getSelectedRow();
            Filme f = bancoFilme.buscaId((int) filmesJTable.getValueAt(linha, 0));
            idJTextField.setText(String.valueOf(f.getId()));
            tituloJTextField.setText(f.getTitulo());
            autorJTextField.setText(f.getAutor());
            descricaoJTextField.setText(f.getDescricao());
            duracaoJTextField.setText(String.valueOf(f.getDuracao()));
            valorJTextField.setText(String.valueOf(f.getValorLocacao()));
            qntdJTextField.setText(String.valueOf(f.getQntdEstoque()));
            
            //generosSelecionados = f.getGenerosFilme();
            //mostraGeneros();
            
        } else{
            JOptionPane.showMessageDialog(editarJButton, "Selecione 1 cliente!");
        }
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void removerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerJButtonActionPerformed
        int[] linhas = filmesJTable.getSelectedRows();
        if (linhas.length > 1){
            textoExclJLabel.setText("Excluir " + linhas.length + " registros?");
            confirmaExclJDialog.setVisible(true);
        }  else if (linhas.length == 1){
            textoExclJLabel.setText("Excluir " + filmesJTable.getValueAt(linhas[0], 1) + ", ID: " + filmesJTable.getValueAt(linhas[0], 0) + "?");
            confirmaExclJDialog.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(removerJButton, "Escolha um registro para excluir!");
        }
    }//GEN-LAST:event_removerJButtonActionPerformed

    private void simJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simJButtonActionPerformed
        int[] linhas = filmesJTable.getSelectedRows();
        for (int selecionado : linhas){
            Object id = filmesJTable.getValueAt(selecionado, 0);
            Filme apagado = new Filme();
            apagado.setId((int)id);
            bancoFilme.remover(apagado);
        }
        confirmaExclJDialog.setVisible(false);
        carregarTabelaFilmes();
    }//GEN-LAST:event_simJButtonActionPerformed

    private void naoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoJButtonActionPerformed
        confirmaExclJDialog.setVisible(false);
    }//GEN-LAST:event_naoJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarGeneroJButton;
    private javax.swing.JLabel autorJLabel;
    private javax.swing.JTextField autorJTextField;
    private javax.swing.JTextField buscaJTextField;
    private javax.swing.JButton buscarJButton;
    private javax.swing.JButton cadastrarJButton;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JDialog confirmaExclJDialog;
    private javax.swing.JTextField descricaoJTextField;
    private javax.swing.JLabel descriçãoJLabel;
    private javax.swing.JLabel duracaoJLabel;
    private javax.swing.JTextField duracaoJTextField;
    private javax.swing.JButton editarJButton;
    private javax.swing.JTable filmesJTable;
    private javax.swing.JComboBox<String> generosJComboBox;
    private javax.swing.JLabel generosJLabel;
    private javax.swing.JTextField generosJTextField;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton naoJButton;
    private javax.swing.JLabel qntdJLabel;
    private javax.swing.JTextField qntdJTextField;
    private javax.swing.JButton removerGeneroJButton;
    private javax.swing.JButton removerJButton;
    private javax.swing.JButton simJButton;
    private javax.swing.JLabel textoCadastroJLabel;
    private javax.swing.JLabel textoExclJLabel;
    private javax.swing.JLabel tituloJLabel;
    private javax.swing.JLabel tituloJLabel1;
    private javax.swing.JTextField tituloJTextField;
    private javax.swing.JLabel valorJLabel;
    private javax.swing.JTextField valorJTextField;
    // End of variables declaration//GEN-END:variables
}
