/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Cliente;
import locadora.random.play.persistencia.ClienteDAOImplPsql;
/**
 *
 * @author kauan
 */
public class CadastraClienteJPanel extends javax.swing.JPanel {
    private ClienteDAOImplPsql banco = new ClienteDAOImplPsql();
    /**
     * Creates new form ClienteJPanel
     */
    
    public CadastraClienteJPanel() {
        initComponents();
        carregarTabela();
    }
    private void carregarTabela(){
        DefaultTableModel dfm = (DefaultTableModel) clientesJTable.getModel();
        dfm.setRowCount(0);
        
        List<Cliente> lista = banco.consultarLimitado(20);
        for (Cliente cliente : lista) {
            Object[] linha = new Object[6];
            linha[0] = cliente.getId();
            linha[1] = cliente.getNome();
            linha[2] = cliente.getCpf();
            linha[3] = cliente.getDataNasc();
            linha[4] = cliente.getEmail();
            linha[5] = cliente.getEndereco();
            dfm.addRow(linha);
        }
    }
    private void resultaBuscaNome(String nome){
        DefaultTableModel dfm = (DefaultTableModel) clientesJTable.getModel();
        dfm.setRowCount(0);
        
        List<Cliente> lista = banco.buscarNome(nome);
        for (Cliente cliente : lista) {
            Object[] linha = new Object[6];
            linha[0] = cliente.getId();
            linha[1] = cliente.getNome();
            linha[2] = cliente.getCpf();
            linha[3] = cliente.getDataNasc();
            linha[4] = cliente.getEmail();
            linha[5] = cliente.getEndereco();
            dfm.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaExclJDialog = new javax.swing.JDialog();
        simJButton = new javax.swing.JButton();
        naoJButton = new javax.swing.JButton();
        textoExclJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        nomeJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        dataNascJLabel = new javax.swing.JLabel();
        dataNascJFormattedTextField = new javax.swing.JFormattedTextField();
        cpfJLabel = new javax.swing.JLabel();
        cpfJFormattedTextField = new javax.swing.JFormattedTextField();
        tituloTabelaJLabel = new javax.swing.JLabel();
        enderecolJLabel = new javax.swing.JLabel();
        enderecoJTextField = new javax.swing.JTextField();
        cadastrarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        clientesJTable = new javax.swing.JTable();
        editarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        tituloJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        buscarJButton = new javax.swing.JButton();
        buscaJTextField = new javax.swing.JTextField();

        confirmaExclJDialog.setSize(new java.awt.Dimension(330, 190));

        simJButton.setText("Sim");
        simJButton.addActionListener(this::simJButtonActionPerformed);

        naoJButton.setText("Não");
        naoJButton.addActionListener(this::naoJButtonActionPerformed);

        textoExclJLabel.setText("TEXTO DE EXCLUSÃO");

        javax.swing.GroupLayout confirmaExclJDialogLayout = new javax.swing.GroupLayout(confirmaExclJDialog.getContentPane());
        confirmaExclJDialog.getContentPane().setLayout(confirmaExclJDialogLayout);
        confirmaExclJDialogLayout.setHorizontalGroup(
            confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoExclJLabel)
                    .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                        .addComponent(simJButton)
                        .addGap(39, 39, 39)
                        .addComponent(naoJButton)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        confirmaExclJDialogLayout.setVerticalGroup(
            confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(textoExclJLabel)
                .addGap(40, 40, 40)
                .addGroup(confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simJButton)
                    .addComponent(naoJButton))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        idJLabel.setText("ID:");

        idJTextField.setEditable(false);
        idJTextField.setEnabled(false);
        idJTextField.addActionListener(this::idJTextFieldActionPerformed);

        nomeJLabel.setText("Nome:");

        dataNascJLabel.setText("Data de nascimento:");

        try {
            dataNascJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cpfJLabel.setText("Cpf:");

        try {
            cpfJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tituloTabelaJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloTabelaJLabel.setText("CLIENTES CADASTRADOS");

        enderecolJLabel.setText("Endereço:");

        enderecoJTextField.addActionListener(this::enderecoJTextFieldActionPerformed);

        cadastrarJButton.setText("Cadastrar");
        cadastrarJButton.addActionListener(this::cadastrarJButtonActionPerformed);

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        clientesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Data de Nasc", "Email", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientesJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(clientesJTable);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        tituloJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloJLabel.setText("CADASTRAR CLIENTE");

        emailJLabel.setText("Email:");

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(this::buscarJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dataNascJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(dataNascJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(cadastrarJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                            .addComponent(cancelarJButton)
                            .addGap(22, 22, 22))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeJLabel)
                                .addComponent(idJLabel)
                                .addComponent(cpfJLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enderecolJLabel)
                                .addComponent(emailJLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(enderecoJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                .addComponent(emailJTextField))))
                    .addComponent(tituloJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(atualizarJButton)
                        .addGap(232, 232, 232)
                        .addComponent(editarJButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluirJButton))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTabelaJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTabelaJLabel)
                    .addComponent(tituloJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJLabel)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarJButton)
                    .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeJLabel)
                            .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfJLabel)
                            .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataNascJLabel)
                            .addComponent(dataNascJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailJLabel)
                            .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enderecolJLabel)
                            .addComponent(enderecoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarJButton)
                            .addComponent(cancelarJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(excluirJButton)
                                .addComponent(editarJButton))
                            .addComponent(atualizarJButton))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJTextFieldActionPerformed

    private void enderecoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoJTextFieldActionPerformed

    private void cadastrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJButtonActionPerformed
        try {
        Cliente novoCliente = new Cliente(nomeJTextField.getText(), dataNascJFormattedTextField.getText(), cpfJFormattedTextField.getText(), enderecoJTextField.getText(), emailJTextField.getText());
        String idStr = idJTextField.getText();  
            try {
                int id = Integer.parseInt(idStr);
                novoCliente.setId(id);
                banco.atualizar(novoCliente);
                JOptionPane.showMessageDialog(cadastrarJButton, "Cliente atualizado!");                
            } catch(NumberFormatException erro){
            //Verificar se o cpf já está no sistema
                List<Cliente> listaCliente = banco.consultar();
                String cpf0 = novoCliente.getCpf();
                boolean cadastrado = false;
                for (Cliente c : listaCliente){
                if (c.getCpf().equals(cpf0)){
                    JOptionPane.showMessageDialog(cadastrarJButton, "CPF já registrado!");
                    cadastrado = true;
                    break;
                }
            }        
            //Fim verificaçõa
            if (!cadastrado){
                banco.inserir(novoCliente);
                JOptionPane.showMessageDialog(cadastrarJButton, "Cliente cadastrado com sucesso!");
                cancelarJButtonActionPerformed(evt);
            }}
        
            } catch(Exception erro) {
            erro.printStackTrace();
            JOptionPane.showMessageDialog(cadastrarJButton, erro.getMessage());
        }
        carregarTabela();
    }//GEN-LAST:event_cadastrarJButtonActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        idJTextField.setText("");
        nomeJTextField.setText("");
        dataNascJFormattedTextField.setValue(null);
        cpfJFormattedTextField.setValue(null);
        enderecoJTextField.setText("");
        emailJTextField.setText("");
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int[] linhas = clientesJTable.getSelectedRows();
        if (linhas.length > 1){
            textoExclJLabel.setText("Excluir " + linhas.length + " registros?");
            confirmaExclJDialog.setVisible(true);
        }  else if (linhas.length == 1){
            textoExclJLabel.setText("Excluir " + clientesJTable.getValueAt(linhas[0], 1) + ", CPF: " + clientesJTable.getValueAt(linhas[0], 2) + "?");
            confirmaExclJDialog.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(excluirJButton, "Escolha um registro para excluir!");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        carregarTabela();
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        if (clientesJTable.getSelectedRowCount() == 1){
            int linha = clientesJTable.getSelectedRow();
            Object id = clientesJTable.getValueAt(linha, 0);
            idJTextField.setText(id.toString());
            
            Object nome = clientesJTable.getValueAt(linha, 1);
            nomeJTextField.setText(nome.toString());
            
            Object cpf = clientesJTable.getValueAt(linha, 2);
            cpfJFormattedTextField.setText(cpf.toString());
            
            Object dataNasc = clientesJTable.getValueAt(linha, 3);
            dataNascJFormattedTextField.setText(dataNasc.toString());
            
            Object email = clientesJTable.getValueAt(linha, 4);
            emailJTextField.setText(email.toString());
            
            Object endereco = clientesJTable.getValueAt(linha, 5);
            enderecoJTextField.setText(endereco.toString());
            
        } else{
            JOptionPane.showMessageDialog(editarJButton, "Selecione 1 cliente!");
        }
        
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void simJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simJButtonActionPerformed
        int[] linhas = clientesJTable.getSelectedRows();
        for (int selecionado : linhas){
            Object id = clientesJTable.getValueAt(selecionado, 0);
            Cliente apagado = new Cliente();
            apagado.setId((int)id);
            banco.remover(apagado);
        }
        confirmaExclJDialog.setVisible(false);
        carregarTabela();
    }//GEN-LAST:event_simJButtonActionPerformed

    private void naoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoJButtonActionPerformed
        confirmaExclJDialog.setVisible(false);
    }//GEN-LAST:event_naoJButtonActionPerformed

    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarJButtonActionPerformed
        if (buscaJTextField.getText().isBlank()){
            JOptionPane.showMessageDialog(buscaJTextField, "Digite um nome!");
        }else{
            resultaBuscaNome(buscaJTextField.getText());
        }
    }//GEN-LAST:event_buscarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JTextField buscaJTextField;
    private javax.swing.JButton buscarJButton;
    private javax.swing.JButton cadastrarJButton;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JTable clientesJTable;
    private javax.swing.JDialog confirmaExclJDialog;
    private javax.swing.JFormattedTextField cpfJFormattedTextField;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JFormattedTextField dataNascJFormattedTextField;
    private javax.swing.JLabel dataNascJLabel;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JTextField enderecoJTextField;
    private javax.swing.JLabel enderecolJLabel;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton naoJButton;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JButton simJButton;
    private javax.swing.JLabel textoExclJLabel;
    private javax.swing.JLabel tituloJLabel;
    private javax.swing.JLabel tituloTabelaJLabel;
    // End of variables declaration//GEN-END:variables
}
