/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Cliente;
import locadora.random.play.ItemLocacao;
import locadora.random.play.Locacao;
import locadora.random.play.persistencia.ClienteDAOImplPsql;
import locadora.random.play.persistencia.LocacaoDAOImplPsql;

/**
 *
 * @author kauan
 */
public class DevolucaoJPanel extends javax.swing.JPanel {
    LocacaoDAOImplPsql bancoLocacao = new LocacaoDAOImplPsql();
    ClienteDAOImplPsql bancoCliente = new ClienteDAOImplPsql();
    Cliente cliente = new Cliente();
    
    /**
     * Creates new form DevolverJPanel
     */
    public DevolucaoJPanel() {
        initComponents();
        multaJTextField.setText("R$ 0.00");
    }
    private void carregarTabelaLocacoesCliente(){
        DefaultTableModel dfm = (DefaultTableModel) locacoesJTable.getModel();
        dfm.setRowCount(0);
        cliente = bancoCliente.buscarPorCpf(cpfJFormattedTextField.getText());
        List<Locacao> lista = new ArrayList<>();
        if (cliente != null){
            lista = bancoLocacao.consultarLocacoesAtivasDoCliente(cliente.getId());
            for (Locacao locacao : lista) {
            
                Object[] linha = new Object[4];
                linha[0] = locacao.getId();
                linha[1] = locacao.getDataLocacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                linha[2] = locacao.getDataDevolucao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                linha[3] = locacao.getValorTotal();
                dfm.addRow(linha);
            }
        }   
    }
    
    private void carregarTabelaItens(int id){
        DefaultTableModel dfm = (DefaultTableModel) itensJTable.getModel();
        dfm.setRowCount(0);
        
        List<ItemLocacao> lista = bancoLocacao.consultarItens(id);
        for (ItemLocacao item : lista) {
            
            Object[] linha = new Object[3];
            linha[0] = item.getId();
            linha[1] = bancoLocacao.retornaTitulo(item.getIdFilme());
            linha[2] = item.getValorLocacao();
            dfm.addRow(linha);
        } 
    }
    
    private void calculaMulta(){
        int selecionada = locacoesJTable.getSelectedRow();
        LocalDate dataPrevista = LocalDate.parse((String) locacoesJTable.getValueAt(selecionada, 2), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate dataLocacao = LocalDate.parse((String) locacoesJTable.getValueAt(selecionada, 1), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        int diasAtrasados = (int) ChronoUnit.DAYS.between(dataPrevista, LocalDate.now());
        int diasLocados = (int) ChronoUnit.DAYS.between(dataLocacao, dataPrevista);
        
        
        if (diasAtrasados >= 0){
            Double valorTotal = (Double) locacoesJTable.getValueAt(selecionada, 3);
            Double valorDiario = valorTotal / diasLocados;         
            Double multa = diasAtrasados * valorDiario;
            BigDecimal bd = new BigDecimal(multa);
            bd = bd.setScale(2, RoundingMode.HALF_UP);
            multa = bd.doubleValue();
            multaJTextField.setText("R$ " + multa.toString());
        } else{
            multaJTextField.setText("R$ 0.00");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarJButton = new javax.swing.JButton();
        cpfJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locacoesJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        itensJTable = new javax.swing.JTable();
        devolverJButton = new javax.swing.JButton();
        selecionarJButton = new javax.swing.JButton();
        cpfJFormattedTextField = new javax.swing.JFormattedTextField();
        itensJLabel = new javax.swing.JLabel();
        devolucaoJLabel = new javax.swing.JLabel();
        multaJLabel = new javax.swing.JLabel();
        multaJTextField = new javax.swing.JTextField();
        locacoesJLabel1 = new javax.swing.JLabel();
        selecionadaJLabel = new javax.swing.JLabel();
        selecionadaJTextField = new javax.swing.JTextField();
        limparJButton = new javax.swing.JButton();

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(this::buscarJButtonActionPerformed);

        cpfJLabel.setText("Informe o CPF do cliente:");

        locacoesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Data Locação", "Dev. Prevista", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(locacoesJTable);

        itensJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo Filme", "Valor Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(itensJTable);

        devolverJButton.setText("Devolver");
        devolverJButton.addActionListener(this::devolverJButtonActionPerformed);

        selecionarJButton.setText("Selecionar");
        selecionarJButton.addActionListener(this::selecionarJButtonActionPerformed);

        try {
            cpfJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        itensJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itensJLabel.setText("FILMES DA LOCAÇÃO");
        itensJLabel.setToolTipText("");

        devolucaoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        devolucaoJLabel.setText("DEVOLUÇÃO");
        devolucaoJLabel.setToolTipText("");

        multaJLabel.setText("Multa por Atraso:");

        multaJTextField.setEditable(false);
        multaJTextField.setEnabled(false);
        multaJTextField.setFocusable(false);

        locacoesJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        locacoesJLabel1.setText("LOCAÇÕES DO CLIENTE");
        locacoesJLabel1.setToolTipText("");

        selecionadaJLabel.setText("Locação Selecionada:");

        selecionadaJTextField.setEditable(false);
        selecionadaJTextField.setEnabled(false);
        selecionadaJTextField.setFocusable(false);
        selecionadaJTextField.addActionListener(this::selecionadaJTextFieldActionPerformed);

        limparJButton.setText("Limpar Busca");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selecionarJButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(limparJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selecionadaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selecionadaJTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(multaJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(devolverJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(multaJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(cpfJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarJButton)
                                .addGap(27, 27, 27)
                                .addComponent(itensJLabel)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(devolucaoJLabel)
                .addGap(402, 402, 402))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(locacoesJLabel1)
                    .addContainerGap(681, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(devolucaoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarJButton)
                            .addComponent(cpfJLabel)
                            .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(itensJLabel)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selecionarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multaJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(multaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selecionadaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(limparJButton))
                                .addGap(18, 18, 18)
                                .addComponent(devolverJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selecionadaJLabel)
                                .addGap(77, 77, 77)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(locacoesJLabel1)
                    .addContainerGap(400, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarJButtonActionPerformed
        if (!cpfJFormattedTextField.getText().equals("   .   .   -  ")){
            carregarTabelaLocacoesCliente();
            if(cliente == null){
                JOptionPane.showMessageDialog(buscarJButton, "CPF não encontrado no sistema!");
            } else if (locacoesJTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(buscarJButton, "CPF fornecido não tem locações ativas!");
            }
        }else{
            JOptionPane.showMessageDialog(buscarJButton, "Insira um CPF válido!");
        }
    }//GEN-LAST:event_buscarJButtonActionPerformed

    private void selecionarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarJButtonActionPerformed
        if (locacoesJTable.getSelectedRowCount() == 1){
            calculaMulta();
            carregarTabelaItens((int) locacoesJTable.getValueAt(locacoesJTable.getSelectedRow(), 0));
            selecionadaJTextField.setText(locacoesJTable.getValueAt(locacoesJTable.getSelectedRow(), 0).toString());
        }else{
            JOptionPane.showMessageDialog(selecionarJButton, "Selecione 1 Locação!");
        }
    }//GEN-LAST:event_selecionarJButtonActionPerformed

    private void devolverJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverJButtonActionPerformed
        if(!selecionadaJTextField.getText().isBlank()){
            if(!multaJTextField.getText().equals("R$ 0.00")){
                JOptionPane.showMessageDialog(devolverJButton, "A pagar: " + multaJTextField.getText() + " de multa devido atraso!");
            }
            bancoLocacao.devolver(Integer.parseInt(selecionadaJTextField.getText()));
            JOptionPane.showMessageDialog(devolverJButton, "Locação devolvida com sucesso!");
            limparJButtonActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(devolverJButton, "Selecione 1 Locação!");
        }
    }//GEN-LAST:event_devolverJButtonActionPerformed

    private void selecionadaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionadaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionadaJTextFieldActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        cpfJFormattedTextField.setText("");
        carregarTabelaLocacoesCliente();
        carregarTabelaItens(0);
        selecionadaJTextField.setText("");
        multaJTextField.setText("R$ 0.00");
    }//GEN-LAST:event_limparJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarJButton;
    private javax.swing.JFormattedTextField cpfJFormattedTextField;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JLabel devolucaoJLabel;
    private javax.swing.JButton devolverJButton;
    private javax.swing.JLabel itensJLabel;
    private javax.swing.JTable itensJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel locacoesJLabel1;
    private javax.swing.JTable locacoesJTable;
    private javax.swing.JLabel multaJLabel;
    private javax.swing.JTextField multaJTextField;
    private javax.swing.JLabel selecionadaJLabel;
    private javax.swing.JTextField selecionadaJTextField;
    private javax.swing.JButton selecionarJButton;
    // End of variables declaration//GEN-END:variables
}
