/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Filme;
import locadora.random.play.persistencia.FilmeDAOImplPsql;

/**
 *
 * @author kauan
 */
public class FilmesDetalhesJPanel extends javax.swing.JPanel {
    private FilmeDAOImplPsql banco = new FilmeDAOImplPsql();
    
    /**
     * Creates new form FilmesDetalhesJPanel
     */
    public FilmesDetalhesJPanel() {
        initComponents();
        carregarTabelaFilmes(emEstoqueJCheckBox.isSelected());
    }
    
    private void carregarTabelaFilmes(boolean emEstoque){
        DefaultTableModel dfm = (DefaultTableModel) filmesJTable.getModel();
        dfm.setRowCount(0);
        List<Filme> lista = banco.consultar(emEstoque);
        for (Filme filme : lista) {
            Object[] linha = new Object[8];
            linha[0] = filme.getId();
            linha[1] = filme.getTitulo();
            linha[2] = filme.getAutor();
            linha[3] = filme.getDescricao();
            linha[4] = filme.generosToString();
            linha[5] = filme.getDuracao();
            linha[6] = filme.getQntdEstoque();
            linha[7] = filme.getValorLocacao();
            dfm.addRow(linha);
        }
    }
    
    private void resultaBuscaTitulo(String titulo, boolean emEstoque){
        DefaultTableModel dfm = (DefaultTableModel) filmesJTable.getModel();
        dfm.setRowCount(0);
        
        List<Filme> lista = banco.buscar(titulo, emEstoque);
        for (Filme filme : lista) {
            Object[] linha = new Object[8];
            linha[0] = filme.getId();
            linha[1] = filme.getTitulo();
            linha[2] = filme.getAutor();
            linha[3] = filme.getDescricao();
            linha[4] = filme.generosToString();
            linha[5] = filme.getDuracao();
            linha[6] = filme.getQntdEstoque();
            linha[7] = filme.getValorLocacao();
            dfm.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        filmesJTable = new javax.swing.JTable();
        tituloJLabel1 = new javax.swing.JLabel();
        buscarJLabel = new javax.swing.JLabel();
        buscarJButton = new javax.swing.JButton();
        buscarJTextField = new javax.swing.JTextField();
        emEstoqueJCheckBox = new javax.swing.JCheckBox();
        limparJButton = new javax.swing.JButton();

        filmesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Autor/Diretor", "Descrição", "Gêneros", "Duração (min)", "Qntd", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        filmesJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(filmesJTable);

        tituloJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloJLabel1.setText("FILMES CADASTRADOS");

        buscarJLabel.setText("Buscar por título:");

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(this::buscarJButtonActionPerformed);

        emEstoqueJCheckBox.setText("Mostrar Apenas em estoque");
        emEstoqueJCheckBox.addActionListener(this::emEstoqueJCheckBoxActionPerformed);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(tituloJLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(buscarJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarJButton)
                        .addGap(18, 18, 18)
                        .addComponent(emEstoqueJCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(limparJButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarJLabel)
                    .addComponent(buscarJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarJButton)
                    .addComponent(emEstoqueJCheckBox)
                    .addComponent(limparJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarJButtonActionPerformed
        if (buscarJTextField.getText().isBlank()){
            JOptionPane.showMessageDialog(buscarJTextField, "Digite um titulo!");
        }else{
            resultaBuscaTitulo(buscarJTextField.getText(), emEstoqueJCheckBox.isSelected());
        }
    }//GEN-LAST:event_buscarJButtonActionPerformed

    private void emEstoqueJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emEstoqueJCheckBoxActionPerformed
        if (buscarJTextField.getText().isBlank()){
            carregarTabelaFilmes(emEstoqueJCheckBox.isSelected());
        }else{
            resultaBuscaTitulo(buscarJTextField.getText(), emEstoqueJCheckBox.isSelected());
        }
    }//GEN-LAST:event_emEstoqueJCheckBoxActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        // TODO add your handling code here:
        buscarJTextField.setText("");
        carregarTabelaFilmes(emEstoqueJCheckBox.isSelected());
    }//GEN-LAST:event_limparJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarJButton;
    private javax.swing.JLabel buscarJLabel;
    private javax.swing.JTextField buscarJTextField;
    private javax.swing.JCheckBox emEstoqueJCheckBox;
    private javax.swing.JTable filmesJTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel tituloJLabel1;
    // End of variables declaration//GEN-END:variables
}
