/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Funcionario;
import locadora.random.play.Funcionario;
import locadora.random.play.persistencia.FuncionarioDAOImplPsql;

/**
 *
 * @author kauan
 */
public class FuncionarioJPanel extends javax.swing.JPanel {
    private FuncionarioDAOImplPsql banco = new FuncionarioDAOImplPsql();
    private DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    /**
     * Creates new form FuncionarioJPanel
     */
    public FuncionarioJPanel() {
        initComponents();
        carregarTabela();
    }
    //É implementado de uma forma a qual o admin principal só pode ser alterado diretamente no banco
    private void carregarTabela(){
        DefaultTableModel dfm = (DefaultTableModel) funcionariosJTable.getModel();
        dfm.setRowCount(0);
        
        List<Funcionario> lista = banco.consultar();
        lista.remove(0);
        for (Funcionario funcionario : lista) {
            Object[] linha = new Object[7];
            linha[0] = funcionario.getId();
            linha[1] = funcionario.getNome();
            linha[2] = funcionario.getCpf();
            linha[3] = funcionario.getDataNasc().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            linha[4] = funcionario.getLogin();
            linha[5] = funcionario.getSenha();
            linha[6] = funcionario.isAdminPerm();
            dfm.addRow(linha);
        }
    }

    private void resultaBuscaNome(String nome){
        DefaultTableModel dfm = (DefaultTableModel) funcionariosJTable.getModel();
        dfm.setRowCount(0);
    
        //É implementado de uma forma a qual o admin principal só pode ser alterado diretamente no banco
        List<Funcionario> lista = banco.buscar(nome);
        if (!lista.isEmpty() && lista.get(0).getId() == 1){
            lista.remove(0);
        }
        
        for (Funcionario funcionario : lista) {
            Object[] linha = new Object[7];
            linha[0] = funcionario.getId();
            linha[1] = funcionario.getNome();
            linha[2] = funcionario.getCpf();
            linha[3] = funcionario.getDataNasc().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            linha[4] = funcionario.getLogin();
            linha[5] = funcionario.getSenha();
            linha[6] = funcionario.isAdminPerm();
            dfm.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaExclJDialog = new javax.swing.JDialog();
        simJButton = new javax.swing.JButton();
        naoJButton = new javax.swing.JButton();
        textoExclJLabel = new javax.swing.JLabel();
        tituloJLabel = new javax.swing.JLabel();
        idJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        nomeJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        cpfJLabel = new javax.swing.JLabel();
        cpfJFormattedTextField = new javax.swing.JFormattedTextField();
        dataNascJLabel = new javax.swing.JLabel();
        dataNascJFormattedTextField = new javax.swing.JFormattedTextField();
        loginJLabel = new javax.swing.JLabel();
        senhaJLabel = new javax.swing.JLabel();
        senhaJTextField = new javax.swing.JTextField();
        loginJTextField = new javax.swing.JTextField();
        cancelarJButton = new javax.swing.JButton();
        cadastrarJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        funcionariosJTable = new javax.swing.JTable();
        buscaJTextField = new javax.swing.JTextField();
        buscarJButton = new javax.swing.JButton();
        editarJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        perfilJCheckBox = new javax.swing.JCheckBox();

        confirmaExclJDialog.setSize(new java.awt.Dimension(330, 190));

        simJButton.setText("Sim");
        simJButton.addActionListener(this::simJButtonActionPerformed);

        naoJButton.setText("Não");
        naoJButton.addActionListener(this::naoJButtonActionPerformed);

        textoExclJLabel.setText("TEXTO DE EXCLUSÃO");

        javax.swing.GroupLayout confirmaExclJDialogLayout = new javax.swing.GroupLayout(confirmaExclJDialog.getContentPane());
        confirmaExclJDialog.getContentPane().setLayout(confirmaExclJDialogLayout);
        confirmaExclJDialogLayout.setHorizontalGroup(
            confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoExclJLabel)
                    .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                        .addComponent(simJButton)
                        .addGap(39, 39, 39)
                        .addComponent(naoJButton)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        confirmaExclJDialogLayout.setVerticalGroup(
            confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaExclJDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(textoExclJLabel)
                .addGap(40, 40, 40)
                .addGroup(confirmaExclJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simJButton)
                    .addComponent(naoJButton))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tituloJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloJLabel.setText("CADASTRAR FUNCIONÁRIO");

        idJLabel.setText("ID:");

        idJTextField.setEditable(false);
        idJTextField.setEnabled(false);
        idJTextField.addActionListener(this::idJTextFieldActionPerformed);

        nomeJLabel.setText("Nome:");

        cpfJLabel.setText("Cpf:");

        try {
            cpfJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfJFormattedTextField.addActionListener(this::cpfJFormattedTextFieldActionPerformed);

        dataNascJLabel.setText("Data de nascimento:");

        try {
            dataNascJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        loginJLabel.setText("Login:");

        senhaJLabel.setText("Senha:");

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(this::cancelarJButtonActionPerformed);

        cadastrarJButton.setText("Cadastrar");
        cadastrarJButton.addActionListener(this::cadastrarJButtonActionPerformed);

        funcionariosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Data Nasc", "Login", "Senha", "Admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(funcionariosJTable);

        buscaJTextField.addActionListener(this::buscaJTextFieldActionPerformed);

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(this::buscarJButtonActionPerformed);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        perfilJCheckBox.setText("Perfil Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataNascJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dataNascJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeJLabel)
                            .addComponent(idJLabel)
                            .addComponent(cpfJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarJButton)
                        .addGap(37, 37, 37)
                        .addComponent(cancelarJButton))
                    .addComponent(tituloJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaJLabel)
                            .addComponent(loginJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginJTextField)
                            .addComponent(senhaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(perfilJCheckBox))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(buscaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarJButton)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(atualizarJButton)
                                .addGap(187, 187, 187)
                                .addComponent(editarJButton)
                                .addGap(18, 18, 18)
                                .addComponent(excluirJButton)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloJLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idJLabel)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeJLabel)
                            .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfJLabel)
                            .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataNascJLabel)
                            .addComponent(dataNascJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginJLabel)
                            .addComponent(loginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senhaJLabel)
                            .addComponent(senhaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(perfilJCheckBox)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarJButton)
                            .addComponent(cancelarJButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscaJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarJButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excluirJButton)
                    .addComponent(editarJButton)
                    .addComponent(atualizarJButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJTextFieldActionPerformed

    private void cadastrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarJButtonActionPerformed
        try {
            Funcionario novoFuncionario = new Funcionario();
            novoFuncionario.setNome(nomeJTextField.getText());
            novoFuncionario.setLogin(loginJTextField.getText());
            novoFuncionario.setSenha(senhaJTextField.getText());
            novoFuncionario.setCpf(cpfJFormattedTextField.getText());
            novoFuncionario.setAdminPerm(perfilJCheckBox.isSelected());
            try{
                novoFuncionario.setDataNasc(LocalDate.parse(dataNascJFormattedTextField.getText(), formato));
            }catch (DateTimeParseException e){
                throw new RuntimeException("Data de nascimento inválida");
            }
            
            String idStr = idJTextField.getText();
            try {
                int id = Integer.parseInt(idStr);
                novoFuncionario.setId(id);
                banco.atualizar(novoFuncionario);
                JOptionPane.showMessageDialog(cadastrarJButton, "Funcionario atualizado!");
                cancelarJButtonActionPerformed(evt);
            } catch(NumberFormatException erro){
            //Verificar se o cpf já está no sistema
                List<Funcionario> listaFuncionario = banco.consultar();
                String cpf0 = novoFuncionario.getCpf();
                boolean cadastrado = false;
                for (Funcionario c : listaFuncionario){
                if (c.getCpf().equals(cpf0)){
                    JOptionPane.showMessageDialog(cadastrarJButton, "CPF já registrado!");
                    cadastrado = true;
                    break;
                }
            }        
            //Fim verificaçõa
            if (!cadastrado){
                banco.inserir(novoFuncionario);
                JOptionPane.showMessageDialog(cadastrarJButton, "Funcionario cadastrado com sucesso!");
                cancelarJButtonActionPerformed(evt);
            }}
        
            } catch(Exception erro) {
            erro.printStackTrace();
            JOptionPane.showMessageDialog(cadastrarJButton, erro.getMessage());
        }
        carregarTabela();
    }//GEN-LAST:event_cadastrarJButtonActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        idJTextField.setText("");
        nomeJTextField.setText("");
        cpfJFormattedTextField.setText("");
        dataNascJFormattedTextField.setText("");
        loginJTextField.setText("");
        senhaJTextField.setText("");
        perfilJCheckBox.setSelected(false);
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int[] linhas = funcionariosJTable.getSelectedRows();
        if (linhas.length > 1){
            textoExclJLabel.setText("Excluir " + linhas.length + " registros?");
            confirmaExclJDialog.setVisible(true);
        }  else if (linhas.length == 1){
            textoExclJLabel.setText("Excluir " + funcionariosJTable.getValueAt(linhas[0], 1) + ", CPF: " + funcionariosJTable.getValueAt(linhas[0], 2) + "?");
            confirmaExclJDialog.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(excluirJButton, "Escolha um registro para excluir!");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void simJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simJButtonActionPerformed
        int[] linhas = funcionariosJTable.getSelectedRows();
        for (int selecionado : linhas){
            Object id = funcionariosJTable.getValueAt(selecionado, 0);
            Funcionario apagado = new Funcionario();
            apagado.setId((int)id);
            banco.remover(apagado);
        }
        confirmaExclJDialog.setVisible(false);
        carregarTabela();
    }//GEN-LAST:event_simJButtonActionPerformed

    private void naoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoJButtonActionPerformed
        confirmaExclJDialog.setVisible(false);
    }//GEN-LAST:event_naoJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        if (funcionariosJTable.getSelectedRowCount() == 1){
            int linha = funcionariosJTable.getSelectedRow();
            Object id = funcionariosJTable.getValueAt(linha, 0);
            idJTextField.setText(id.toString());
            
            Object nome = funcionariosJTable.getValueAt(linha, 1);
            nomeJTextField.setText(nome.toString());
            
            Object dataNasc = funcionariosJTable.getValueAt(linha, 3);
            dataNascJFormattedTextField.setText(dataNasc.toString());
            
            Object cpf = funcionariosJTable.getValueAt(linha, 2);
            cpfJFormattedTextField.setText(cpf.toString());
            
            Object login = funcionariosJTable.getValueAt(linha, 4);
            loginJTextField.setText(login.toString());
            
            Object senha = funcionariosJTable.getValueAt(linha, 5);
            senhaJTextField.setText(senha.toString());
           
            Object admin = funcionariosJTable.getValueAt(linha, 6);
            perfilJCheckBox.setSelected((boolean) admin);
            
        } else{
            JOptionPane.showMessageDialog(editarJButton, "Selecione 1 funcionário!");
        }
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void cpfJFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfJFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfJFormattedTextFieldActionPerformed

    private void buscaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaJTextFieldActionPerformed

    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarJButtonActionPerformed
        if (buscaJTextField.getText().isBlank()){
            JOptionPane.showMessageDialog(buscaJTextField, "Digite um nome!");
        }else{
            resultaBuscaNome(buscaJTextField.getText());
        }

    }//GEN-LAST:event_buscarJButtonActionPerformed

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        carregarTabela();
    }//GEN-LAST:event_atualizarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JTextField buscaJTextField;
    private javax.swing.JButton buscarJButton;
    private javax.swing.JButton cadastrarJButton;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JDialog confirmaExclJDialog;
    private javax.swing.JFormattedTextField cpfJFormattedTextField;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JFormattedTextField dataNascJFormattedTextField;
    private javax.swing.JLabel dataNascJLabel;
    private javax.swing.JButton editarJButton;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JTable funcionariosJTable;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JTextField loginJTextField;
    private javax.swing.JButton naoJButton;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JCheckBox perfilJCheckBox;
    private javax.swing.JLabel senhaJLabel;
    private javax.swing.JTextField senhaJTextField;
    private javax.swing.JButton simJButton;
    private javax.swing.JLabel textoExclJLabel;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
