/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Genero;
import locadora.random.play.persistencia.GeneroDAOImplPsql;

/**
 *
 * @author kauan
 */
public class GeneroJPanel extends javax.swing.JPanel {
    private GeneroDAOImplPsql banco = new GeneroDAOImplPsql();

    /**
     * Creates new form GeneroJPanel
     */
    public GeneroJPanel() {
        initComponents();
        carregarTabela();
    }
    private void carregarTabela(){
        DefaultTableModel dfm = (DefaultTableModel) generosJTable.getModel();
        dfm.setRowCount(0);
        
        List<Genero> lista = banco.consultar();
        for (Genero genero : lista) {
            Object[] linha = new Object[5];
            linha[0] = genero.getId();
            linha[1] = genero.getDescricao();
            dfm.addRow(linha);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJLabel = new javax.swing.JLabel();
        generoJLabel = new javax.swing.JLabel();
        descricaoJTextField = new javax.swing.JTextField();
        adicionarJButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        generosJTable = new javax.swing.JTable();
        editarJButton = new javax.swing.JButton();
        idJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        limparJButton = new javax.swing.JButton();

        tituloJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloJLabel.setText("ADICIONAR NOVO GÊNERO");

        generoJLabel.setText("Descrição do gênero:");

        adicionarJButton.setText("Adicionar");
        adicionarJButton.addActionListener(this::adicionarJButtonActionPerformed);

        generosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id_gênero", "Descricao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        generosJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(generosJTable);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(this::editarJButtonActionPerformed);

        idJLabel.setText("ID:");

        idJTextField.setEditable(false);
        idJTextField.setEnabled(false);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(idJLabel)
                .addGap(18, 18, 18)
                .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generoJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(descricaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(adicionarJButton)
                .addGap(18, 18, 18)
                .addComponent(limparJButton)
                .addContainerGap(98, Short.MAX_VALUE))
            .addComponent(jScrollPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarJButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoJLabel)
                    .addComponent(descricaoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adicionarJButton)
                    .addComponent(idJLabel)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparJButton))
                .addGap(13, 13, 13)
                .addComponent(editarJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarJButtonActionPerformed
        try {
        Genero novoGenero = new Genero(descricaoJTextField.getText());
        String idStr = idJTextField.getText();
        //Verificar se gênero já está no sistema
            List<Genero> listaGenero = banco.consultar();
            String Genero0 = novoGenero.getDescricao();
            boolean cadastrado = false;
            for (Genero g : listaGenero){
                if (g.getDescricao().equals(Genero0)){
                    JOptionPane.showMessageDialog(adicionarJButton, "Gênero já inserido no sistema!");
                    cadastrado = true;
                    break;
                }
            }        
            //Fim verificaçõa
            //insere:
            if (!cadastrado && !descricaoJTextField.getText().isBlank()){
                try {
                    int id = Integer.parseInt(idStr);
                    novoGenero.setId(id);
                    banco.atualizar(novoGenero);
                    JOptionPane.showMessageDialog(adicionarJButton, "Gênero atualizado com sucesso!");                    
            } catch(NumberFormatException erro){
                banco.inserir(novoGenero);
                JOptionPane.showMessageDialog(adicionarJButton, "Gênero inserido com sucesso!");
            }
                limparJButtonActionPerformed(evt);
            }} catch(Exception erro) {
            erro.printStackTrace();
            JOptionPane.showMessageDialog(adicionarJButton, erro.getMessage());
        }
        carregarTabela();
    }//GEN-LAST:event_adicionarJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        if (generosJTable.getSelectedRowCount() == 1){
            int selecionado = generosJTable.getSelectedRow();
            idJTextField.setText(generosJTable.getValueAt(selecionado, 0).toString());
            descricaoJTextField.setText(generosJTable.getValueAt(selecionado, 1).toString());
        }else {
            JOptionPane.showMessageDialog(editarJButton, "Selecione um gênero para editar");
        }
        
    }//GEN-LAST:event_editarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        idJTextField.setText("");
        descricaoJTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarJButton;
    private javax.swing.JTextField descricaoJTextField;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel generoJLabel;
    private javax.swing.JTable generosJTable;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
