/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

/**
 *
 * @author kauan
 */
public class HomeJPanel extends javax.swing.JPanel {

    private TelaJFrame tela;
    /**
     * Creates new form HomeJPanel
     */
    public HomeJPanel(TelaJFrame tela) {
        initComponents();
        this.tela = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLoginJLabel = new javax.swing.JLabel();
        locacaoJButton = new javax.swing.JButton();
        filmeJButton = new javax.swing.JButton();
        sairJButton = new javax.swing.JButton();
        clienteJButton = new javax.swing.JButton();
        devolverJButton1 = new javax.swing.JButton();

        tituloLoginJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloLoginJLabel.setText("Bem Vindo ao Sistema Random Play!");

        locacaoJButton.setText("Nova Locação");
        locacaoJButton.addActionListener(this::locacaoJButtonActionPerformed);

        filmeJButton.setText("Buscar Filme");
        filmeJButton.addActionListener(this::filmeJButtonActionPerformed);

        sairJButton.setText("Sair");
        sairJButton.addActionListener(this::sairJButtonActionPerformed);

        clienteJButton.setText("Cadastrar Cliente");
        clienteJButton.addActionListener(this::clienteJButtonActionPerformed);

        devolverJButton1.setText("Devolver Locação");
        devolverJButton1.addActionListener(this::devolverJButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLoginJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filmeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(devolverJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locacaoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tituloLoginJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locacaoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devolverJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(sairJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locacaoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locacaoJButtonActionPerformed
        // TODO add your handling code here:]
        NovaLocacaoJPanel jpanel = new NovaLocacaoJPanel();
        tela.abreAtalho(jpanel);
    }//GEN-LAST:event_locacaoJButtonActionPerformed

    private void clienteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteJButtonActionPerformed
        // TODO add your handling code here:
        CadastraClienteJPanel jpanel = new CadastraClienteJPanel();
        tela.abreAtalho(jpanel);
    }//GEN-LAST:event_clienteJButtonActionPerformed

    private void filmeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmeJButtonActionPerformed
        // TODO add your handling code here:
        FilmesDetalhesJPanel jpanel = new FilmesDetalhesJPanel();
        tela.abreAtalho(jpanel);
    }//GEN-LAST:event_filmeJButtonActionPerformed

    private void sairJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairJButtonActionPerformed
        // TODO add your handling code here:
        tela.sair();
    }//GEN-LAST:event_sairJButtonActionPerformed

    private void devolverJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverJButton1ActionPerformed
        // TODO add your handling code here:
        DevolucaoJPanel jpanel = new DevolucaoJPanel();
        tela.abreAtalho(jpanel);
    }//GEN-LAST:event_devolverJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteJButton;
    private javax.swing.JButton devolverJButton1;
    private javax.swing.JButton filmeJButton;
    private javax.swing.JButton locacaoJButton;
    private javax.swing.JButton sairJButton;
    private javax.swing.JLabel tituloLoginJLabel;
    // End of variables declaration//GEN-END:variables
}
