/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.random.play.Cliente;
import locadora.random.play.ItemLocacao;
import locadora.random.play.Locacao;
import locadora.random.play.persistencia.ClienteDAOImplPsql;
import locadora.random.play.persistencia.LocacaoDAOImplPsql;

/**
 *
 * @author kauan
 */
public class LocacoesRegistradasJPanel extends javax.swing.JPanel {
    LocacaoDAOImplPsql bancoLocacao = new LocacaoDAOImplPsql();
    ClienteDAOImplPsql bancoCliente = new ClienteDAOImplPsql();
    Cliente cliente = new Cliente();
    /**
     * Creates new form BuscaLocacaoJPanel
     */
    public LocacoesRegistradasJPanel() {
        initComponents();
        carregarTabelaLocacoes(filtroJCheckBox.isSelected());
    }

    private void carregarTabelaLocacoes(boolean apenasAtivas){
        DefaultTableModel dfm = (DefaultTableModel) locacoesJTable.getModel();
        dfm.setRowCount(0);
        List<Locacao> lista = new ArrayList<>();
        if(apenasAtivas){
                lista = bancoLocacao.consultarLocacoesAtivas();
            }else{
                lista = bancoLocacao.consultarLocacoes();
            }
        for (Locacao locacao : lista) {
            
            Object[] linha = new Object[5];
            linha[0] = locacao.getId();
            linha[1] = bancoCliente.retornaNome(locacao.getIdCliente());
            linha[2] = locacao.getDataLocacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            if(locacao.getDataDevolucaoReal() != null){
                linha[3] = locacao.getDataDevolucaoReal().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            }else{
                linha[3] = locacao.getDataDevolucao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            }
            linha[4] = locacao.getValorTotal();
            dfm.addRow(linha);
        }
    }
    
    private void carregarTabelaLocacoesCliente(boolean apenasAtivas){
        DefaultTableModel dfm = (DefaultTableModel) locacoesJTable.getModel();
        dfm.setRowCount(0);
        cliente = bancoCliente.buscarPorCpf(cpfJFormattedTextField.getText());
        List<Locacao> lista = new ArrayList<>();
        if (cliente != null){
            if(apenasAtivas){
                lista = bancoLocacao.consultarLocacoesAtivasDoCliente(cliente.getId());
            }else{
                lista = bancoLocacao.consultarLocacoesDoCliente(cliente.getId());
            }
            for (Locacao locacao : lista) {
            
                Object[] linha = new Object[5];
                linha[0] = locacao.getId();
                linha[1] = cliente.getNome();
                linha[2] = locacao.getDataLocacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                if(locacao.getDataDevolucaoReal() != null){
                    linha[3] = locacao.getDataDevolucaoReal().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                }else{
                    linha[3] = locacao.getDataDevolucao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                }
                linha[4] = locacao.getValorTotal();
                dfm.addRow(linha);
            }
            
        }   
    }
    
    private void carregarTabelaItens(int id){
        DefaultTableModel dfm = (DefaultTableModel) itensJTable.getModel();
        dfm.setRowCount(0);
        
        List<ItemLocacao> lista = bancoLocacao.consultarItens(id);
        for (ItemLocacao item : lista) {
            
            Object[] linha = new Object[3];
            linha[0] = item.getId();
            linha[1] = bancoLocacao.retornaTitulo(item.getIdFilme());
            linha[2] = item.getValorLocacao();
            dfm.addRow(linha);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locacoesJTable = new javax.swing.JTable();
        setaFodaJLabel = new javax.swing.JLabel();
        selecionarJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        itensJTable = new javax.swing.JTable();
        locacaoJLabel = new javax.swing.JLabel();
        itensJLabel = new javax.swing.JLabel();
        cpfJFormattedTextField = new javax.swing.JFormattedTextField();
        buscarJButton = new javax.swing.JButton();
        limparJButton = new javax.swing.JButton();
        filtroJCheckBox = new javax.swing.JCheckBox();

        tituloJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloJLabel.setText("LOCAÇÕES REGISTRADAS");

        locacoesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Data Locação", "Data Devolução", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(locacoesJTable);

        setaFodaJLabel.setText("-------->");

        selecionarJButton.setText("Selecionar");
        selecionarJButton.addActionListener(this::selecionarJButtonActionPerformed);

        itensJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Filme", "Valor Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(itensJTable);

        locacaoJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        locacaoJLabel.setText("LOCAÇÃO");
        locacaoJLabel.setToolTipText("");

        itensJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itensJLabel.setText("FILMES LOCADOS");
        itensJLabel.setToolTipText("");

        try {
            cpfJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buscarJButton.setText("Buscar Cliente");
        buscarJButton.addActionListener(this::buscarJButtonActionPerformed);

        limparJButton.setText("Limpar Busca");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        filtroJCheckBox.setText("Mostrar Apenas Locações Ativas");
        filtroJCheckBox.addActionListener(this::filtroJCheckBoxActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filtroJCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(selecionarJButton)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(setaFodaJLabel)
                                        .addGap(43, 43, 43))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(limparJButton)
                                        .addGap(18, 18, 18)))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itensJLabel)
                        .addGap(82, 82, 82))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(locacaoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloJLabel)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(locacaoJLabel)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(itensJLabel)
                                .addComponent(filtroJCheckBox))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buscarJButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(setaFodaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selecionarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limparJButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarJButtonActionPerformed
        if (locacoesJTable.getSelectedRowCount() == 1){
            carregarTabelaItens((int) locacoesJTable.getValueAt(locacoesJTable.getSelectedRow(), 0));
        }else{
            JOptionPane.showMessageDialog(selecionarJButton, "Selecione 1 Locação!");
        } 
    }//GEN-LAST:event_selecionarJButtonActionPerformed

    private void buscarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarJButtonActionPerformed
        if (!cpfJFormattedTextField.getText().equals("   .   .   -  ")){
            carregarTabelaLocacoesCliente(filtroJCheckBox.isSelected());
            if(cliente == null){
                JOptionPane.showMessageDialog(buscarJButton, "CPF não encontrado no sistema!");
            }
        }else{
            JOptionPane.showMessageDialog(buscarJButton, "Insira um CPF válido!");
        }
    }//GEN-LAST:event_buscarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        carregarTabelaLocacoes(filtroJCheckBox.isSelected());
        carregarTabelaItens(0);
        cpfJFormattedTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void filtroJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroJCheckBoxActionPerformed
        if (cpfJFormattedTextField.getText().equals("   .   .   -  ")){
            carregarTabelaLocacoes(filtroJCheckBox.isSelected());
        }else{
            carregarTabelaLocacoesCliente(filtroJCheckBox.isSelected());
        }
        itensJTable.removeAll();
    }//GEN-LAST:event_filtroJCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarJButton;
    private javax.swing.JFormattedTextField cpfJFormattedTextField;
    private javax.swing.JCheckBox filtroJCheckBox;
    private javax.swing.JLabel itensJLabel;
    private javax.swing.JTable itensJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel locacaoJLabel;
    private javax.swing.JTable locacoesJTable;
    private javax.swing.JButton selecionarJButton;
    private javax.swing.JLabel setaFodaJLabel;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
