/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.random.play.ui;

import javax.swing.JOptionPane;
import locadora.random.play.Funcionario;
import locadora.random.play.persistencia.FuncionarioDAOImplPsql;

/**
 *
 * @author kauan
 */
public class LoginJPanel extends javax.swing.JPanel {
    FuncionarioDAOImplPsql banco = new FuncionarioDAOImplPsql();
    TelaJFrame tela;
    
    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel(TelaJFrame tela) {
        initComponents();
        this.tela = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrarJButton = new javax.swing.JButton();
        senhaJPasswordField = new javax.swing.JPasswordField();
        senhaJLabel = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        loginJTextField = new javax.swing.JTextField();
        tituloLoginJLabel = new javax.swing.JLabel();

        entrarJButton.setText("Entrar");
        entrarJButton.addActionListener(this::entrarJButtonActionPerformed);

        senhaJPasswordField.addActionListener(this::senhaJPasswordFieldActionPerformed);

        senhaJLabel.setText("Senha:");

        loginJLabel.setText("Usuário:");

        tituloLoginJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloLoginJLabel.setText("Login:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(entrarJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(tituloLoginJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginJLabel)
                            .addComponent(senhaJLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(tituloLoginJLabel)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaJLabel))
                .addGap(34, 34, 34)
                .addComponent(entrarJButton)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarJButtonActionPerformed
        if (!loginJTextField.getText().isBlank()){
            Funcionario user = banco.logar(loginJTextField.getText(), senhaJPasswordField.getText());
            if (user == null){
                JOptionPane.showMessageDialog(entrarJButton, "Usuário ou senha incorretos!");
            }else{
                tela.logar(user.isAdminPerm(), user.getLogin());
                Sessao.usuario = user;
                loginJTextField.setText("");
                senhaJPasswordField.setText("");
            }}else{
            JOptionPane.showMessageDialog(entrarJButton, "Insira um Login");
        }
    }//GEN-LAST:event_entrarJButtonActionPerformed

    private void senhaJPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaJPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaJPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JTextField loginJTextField;
    private javax.swing.JLabel senhaJLabel;
    private javax.swing.JPasswordField senhaJPasswordField;
    private javax.swing.JLabel tituloLoginJLabel;
    // End of variables declaration//GEN-END:variables
}
