/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.random.play.ui;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import locadora.random.play.Funcionario;
import locadora.random.play.persistencia.FuncionarioDAOImplPsql;

/**
 *
 * @author kauan
 */
public class TelaJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJFrame.class.getName());
    private FuncionarioDAOImplPsql banco = new FuncionarioDAOImplPsql();
    
    /**
     * Creates new form TelaJFrame
     */
    public TelaJFrame() {
        initComponents();
        barraDeFerramentas.setVisible(false);
        LoginJPanel jpanel = new LoginJPanel(this);
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();

    }
    
    public void logar(boolean adminPerm, String login){
        barraDeFerramentas.setVisible(true);
        funcionarioJMenu.setVisible(adminPerm);
        logadoJMenuItem.setText("Logado como: " + login);
        abreHome();
    }
    
    public void abreHome(){
        HomeJPanel jpanel = new HomeJPanel(this);
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }
    public void abreAtalho(JPanel novaTela){
        novaTela.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(novaTela);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conteudoJPanel = new javax.swing.JPanel();
        barraDeFerramentas = new javax.swing.JMenuBar();
        loginJMenu = new javax.swing.JMenu();
        logadoJMenuItem = new javax.swing.JMenuItem();
        homeJMenuItem = new javax.swing.JMenuItem();
        sairJMenuItem = new javax.swing.JMenuItem();
        locacaoJMenu = new javax.swing.JMenu();
        novaLocacaoJMenuItem = new javax.swing.JMenuItem();
        locacoesRegistradasJMenuItem = new javax.swing.JMenuItem();
        devolucaoJMenuItem = new javax.swing.JMenuItem();
        menuClienteJMenu = new javax.swing.JMenu();
        cadastrarClienteMenuItem = new javax.swing.JMenuItem();
        filmeJMenu = new javax.swing.JMenu();
        cadastrarFilmeJMenuItem = new javax.swing.JMenuItem();
        todosFilmesJMenuItem = new javax.swing.JMenuItem();
        generoJMenu = new javax.swing.JMenu();
        cadastrarGeneroJMenuItem = new javax.swing.JMenuItem();
        funcionarioJMenu = new javax.swing.JMenu();
        cadastraEBuscaJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conteudoJPanel.setMaximumSize(new java.awt.Dimension(0, 0));
        conteudoJPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        conteudoJPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout conteudoJPanelLayout = new javax.swing.GroupLayout(conteudoJPanel);
        conteudoJPanel.setLayout(conteudoJPanelLayout);
        conteudoJPanelLayout.setHorizontalGroup(
            conteudoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
        );
        conteudoJPanelLayout.setVerticalGroup(
            conteudoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        loginJMenu.setText("Login");

        logadoJMenuItem.setText("Logado como: Nome da Silva");
        loginJMenu.add(logadoJMenuItem);

        homeJMenuItem.setText("Tela inicial");
        homeJMenuItem.addActionListener(this::homeJMenuItemActionPerformed);
        loginJMenu.add(homeJMenuItem);

        sairJMenuItem.setText("Sair");
        sairJMenuItem.addActionListener(this::sairJMenuItemActionPerformed);
        loginJMenu.add(sairJMenuItem);

        barraDeFerramentas.add(loginJMenu);

        locacaoJMenu.setText("Locação");

        novaLocacaoJMenuItem.setText("Nova Locação");
        novaLocacaoJMenuItem.addActionListener(this::novaLocacaoJMenuItemActionPerformed);
        locacaoJMenu.add(novaLocacaoJMenuItem);

        locacoesRegistradasJMenuItem.setText("Locações Registradas");
        locacoesRegistradasJMenuItem.addActionListener(this::locacoesRegistradasJMenuItemActionPerformed);
        locacaoJMenu.add(locacoesRegistradasJMenuItem);

        devolucaoJMenuItem.setText("Devolução");
        devolucaoJMenuItem.addActionListener(this::devolucaoJMenuItemActionPerformed);
        locacaoJMenu.add(devolucaoJMenuItem);

        barraDeFerramentas.add(locacaoJMenu);

        menuClienteJMenu.setText("Cliente");
        menuClienteJMenu.addActionListener(this::menuClienteJMenuActionPerformed);

        cadastrarClienteMenuItem.setText("Cadastrar/Buscar");
        cadastrarClienteMenuItem.addActionListener(this::cadastrarClienteMenuItemActionPerformed);
        menuClienteJMenu.add(cadastrarClienteMenuItem);

        barraDeFerramentas.add(menuClienteJMenu);

        filmeJMenu.setText("Filmes");

        cadastrarFilmeJMenuItem.setText("Cadastrar");
        cadastrarFilmeJMenuItem.addActionListener(this::cadastrarFilmeJMenuItemActionPerformed);
        filmeJMenu.add(cadastrarFilmeJMenuItem);

        todosFilmesJMenuItem.setText("Todos Filmes");
        todosFilmesJMenuItem.addActionListener(this::todosFilmesJMenuItemActionPerformed);
        filmeJMenu.add(todosFilmesJMenuItem);

        barraDeFerramentas.add(filmeJMenu);

        generoJMenu.setText("Gênero");

        cadastrarGeneroJMenuItem.setText("Cadastrar/Lista");
        cadastrarGeneroJMenuItem.addActionListener(this::cadastrarGeneroJMenuItemActionPerformed);
        generoJMenu.add(cadastrarGeneroJMenuItem);

        barraDeFerramentas.add(generoJMenu);

        funcionarioJMenu.setText("Funcionários");
        funcionarioJMenu.addActionListener(this::funcionarioJMenuActionPerformed);

        cadastraEBuscaJMenuItem.setText("Cadastro e Busca");
        cadastraEBuscaJMenuItem.addActionListener(this::cadastraEBuscaJMenuItemActionPerformed);
        funcionarioJMenu.add(cadastraEBuscaJMenuItem);

        barraDeFerramentas.add(funcionarioJMenu);

        setJMenuBar(barraDeFerramentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conteudoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarClienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteMenuItemActionPerformed
        // TODO add your handling code here:
    CadastraClienteJPanel jpanel = new CadastraClienteJPanel();
    jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
    conteudoJPanel.removeAll();
    conteudoJPanel.add(jpanel);
    conteudoJPanel.revalidate();
    conteudoJPanel.repaint();
    }//GEN-LAST:event_cadastrarClienteMenuItemActionPerformed

    private void menuClienteJMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteJMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuClienteJMenuActionPerformed

    private void cadastrarGeneroJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarGeneroJMenuItemActionPerformed
    GeneroJPanel jpanel = new GeneroJPanel();
    jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
    conteudoJPanel.removeAll();
    conteudoJPanel.add(jpanel);
    conteudoJPanel.revalidate();
    conteudoJPanel.repaint();
    }//GEN-LAST:event_cadastrarGeneroJMenuItemActionPerformed

    private void funcionarioJMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioJMenuActionPerformed
    }//GEN-LAST:event_funcionarioJMenuActionPerformed

    private void cadastraEBuscaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraEBuscaJMenuItemActionPerformed
    FuncionarioJPanel jpanel = new FuncionarioJPanel();
    jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
    conteudoJPanel.removeAll();
    conteudoJPanel.add(jpanel);
    conteudoJPanel.revalidate();
    conteudoJPanel.repaint();
    }//GEN-LAST:event_cadastraEBuscaJMenuItemActionPerformed

    private void sairJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairJMenuItemActionPerformed
        LoginJPanel jpanel = new LoginJPanel(this);
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
        barraDeFerramentas.setVisible(false);
    }//GEN-LAST:event_sairJMenuItemActionPerformed

    private void cadastrarFilmeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFilmeJMenuItemActionPerformed
        CadastraFilmeJPanel jpanel = new CadastraFilmeJPanel();
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_cadastrarFilmeJMenuItemActionPerformed

    private void novaLocacaoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaLocacaoJMenuItemActionPerformed
        NovaLocacaoJPanel jpanel = new NovaLocacaoJPanel();
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_novaLocacaoJMenuItemActionPerformed

    private void locacoesRegistradasJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locacoesRegistradasJMenuItemActionPerformed
        LocacoesRegistradasJPanel jpanel = new LocacoesRegistradasJPanel();
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_locacoesRegistradasJMenuItemActionPerformed

    private void devolucaoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucaoJMenuItemActionPerformed
        DevolucaoJPanel jpanel = new DevolucaoJPanel();
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_devolucaoJMenuItemActionPerformed

    private void todosFilmesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosFilmesJMenuItemActionPerformed
        FilmesDetalhesJPanel jpanel = new FilmesDetalhesJPanel();
        jpanel.setSize(conteudoJPanel.getWidth(), conteudoJPanel.getHeight());
        conteudoJPanel.removeAll();
        conteudoJPanel.add(jpanel);
        conteudoJPanel.revalidate();
        conteudoJPanel.repaint();
    }//GEN-LAST:event_todosFilmesJMenuItemActionPerformed

    private void homeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJMenuItemActionPerformed
        // TODO add your handling code here:
        abreHome();
    }//GEN-LAST:event_homeJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeFerramentas;
    private javax.swing.JMenuItem cadastraEBuscaJMenuItem;
    private javax.swing.JMenuItem cadastrarClienteMenuItem;
    private javax.swing.JMenuItem cadastrarFilmeJMenuItem;
    private javax.swing.JMenuItem cadastrarGeneroJMenuItem;
    private javax.swing.JPanel conteudoJPanel;
    private javax.swing.JMenuItem devolucaoJMenuItem;
    private javax.swing.JMenu filmeJMenu;
    private javax.swing.JMenu funcionarioJMenu;
    private javax.swing.JMenu generoJMenu;
    private javax.swing.JMenuItem homeJMenuItem;
    private javax.swing.JMenu locacaoJMenu;
    private javax.swing.JMenuItem locacoesRegistradasJMenuItem;
    private javax.swing.JMenuItem logadoJMenuItem;
    private javax.swing.JMenu loginJMenu;
    private javax.swing.JMenu menuClienteJMenu;
    private javax.swing.JMenuItem novaLocacaoJMenuItem;
    private javax.swing.JMenuItem sairJMenuItem;
    private javax.swing.JMenuItem todosFilmesJMenuItem;
    // End of variables declaration//GEN-END:variables
}
